#!/bin/bash
# test-map-verify.sh — behavior contract for auto-map's anti-lie gate (CI-run).
# The verifier must PASS a correct disclosure-tiered map and CATCH every class of lie:
# phantom paths, launch-time @imports, budget blowouts, unscoped rules, unmarked commands,
# missing stamps, and unmapped significant directories.
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
V="$ROOT/auto-map/scripts/verify-map.mjs"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
fails=0
want() { # want <rc> <desc> <args...>
  local rc=$1 desc=$2; shift 2
  node "$V" "$@" >/dev/null 2>&1
  local got=$?
  [ "$got" = "$rc" ] && echo "PASS ($got) $desc" || { echo "FAIL (got $got want $rc) $desc"; fails=$((fails+1)); }
}
grepv() { # grepv <desc> <pattern> <args...>
  local desc=$1 pat=$2; shift 2
  if node "$V" "$@" 2>&1 | grep -q "$pat"; then echo "PASS (caught) $desc"; else { echo "FAIL (not caught) $desc"; fails=$((fails+1)); }; fi
}

# ── GOOD map: tiered, stamped, scoped, real paths, marked commands ──
G="$TMP/good"; mkdir -p "$G/src/api" "$G/.claude/rules"
cat > "$G/CLAUDE.md" <<'EOF'
<!-- generated by auto-map v0.1.0 -->
# Proj
Small demo service.
## Commands
- `npm test` — run the suite (verified: 2026-07-06)
## Layout
- `src/api/` — HTTP handlers (see its CLAUDE.md)
EOF
cat > "$G/.claude/rules/api.md" <<'EOF'
---
paths:
  - "src/api/**"
---
# API conventions
Validate all input at the boundary.
EOF
cat > "$G/src/api/CLAUDE.md" <<'EOF'
<!-- generated by auto-map v0.1.0 -->
# src/api
HTTP handlers. Never touch the DB directly — go through `src/api/index.ts`.
EOF
touch "$G/src/api/index.ts"
want 0 "correct tiered map verifies clean" "$G"

# ── LIES: each class must be caught ──
B="$TMP/bad"; mkdir -p "$B/src/api" "$B/.claude/rules"
cat > "$B/CLAUDE.md" <<'EOF'
# Proj
See @docs/architecture.md for detail.
- `npm test` — run the suite
- `src/ghost/missing.ts` — the core module
EOF
cat > "$B/.claude/rules/api.md" <<'EOF'
# API conventions (no paths frontmatter — loads every session)
Rule text.
EOF
grepv "phantom path caught"        "does not exist"        "$B"
grepv "@import caught"             "imports load AT LAUNCH" "$B"
grepv "unmarked command caught"    "no (verified)"          "$B"
grepv "missing stamp caught"       "generation stamp"       "$B"
grepv "unscoped rules file caught" "paths:"                 "$B"
want 1 "lying map exits 1" "$B"

# budget blowout
python3 -c "open('$B/src/api/CLAUDE.md','w').write('x line\n' * 130)"
grepv "nested budget blowout caught" "over budget" "$B"

# expected significant dirs
mkdir -p "$G/src/db"
grepv "unmapped significant dir caught" "no nested CLAUDE.md" "$G" --expect-dirs "src/db"
want 0 "expected dir satisfied when mapped is absent from list" "$G" --expect-dirs "src/api"

# command execution mode: failing command caught
F="$TMP/cmd"; mkdir -p "$F"
printf '<!-- generated by auto-map v0.1.0 -->\n# P\n- `npm run definitely-not-a-script` — build\n' > "$F/CLAUDE.md"
grepv "failing command caught (--run-commands)" "FAILS when executed" "$F" --run-commands

# no map at all
want 2 "no map exits 2" "$TMP/empty-$$-nonexistent" 2>/dev/null || true
mkdir -p "$TMP/nomap" && want 2 "dir without CLAUDE.md exits 2" "$TMP/nomap"

# ══ Codex platform: root + nested AGENTS.md, .claude/rules NOT required ══
CG="$TMP/codex-good"; mkdir -p "$CG/src/api"
cat > "$CG/AGENTS.md" <<'EOF'
<!-- generated by auto-map v0.1.0 | 2026-07-06 | scope: root | platform: codex -->
# Proj
Small demo service.
## Commands
- `npm test` — run the suite (verified: 2026-07-06)
## Layout
- `src/api/` — HTTP handlers (see its AGENTS.md)
EOF
cat > "$CG/src/api/AGENTS.md" <<'EOF'
<!-- generated by auto-map v0.1.0 | 2026-07-06 | scope: src/api | platform: codex -->
# src/api
HTTP handlers. Never touch the DB directly — go through `src/api/index.ts`.
EOF
touch "$CG/src/api/index.ts"
want 0 "codex root+nested AGENTS.md verifies clean WITHOUT .claude/rules" "$CG" --platform codex
want 0 "codex satisfied when expected dir is mapped (AGENTS.md)" "$CG" --platform codex --expect-dirs "src/api"

# codex looks for AGENTS.md, not CLAUDE.md: a CLAUDE-only project has no codex root map → exit 2
CO="$TMP/codex-onlyclaude"; mkdir -p "$CO"
printf '<!-- generated by auto-map v0.1.0 -->\n# P\n' > "$CO/CLAUDE.md"
want 2 "codex exits 2 when only CLAUDE.md exists (no root AGENTS.md)" "$CO" --platform codex

# codex: each lie class caught inside AGENTS.md
CB="$TMP/codex-bad"; mkdir -p "$CB/src/api"
cat > "$CB/AGENTS.md" <<'EOF'
# Proj
- `npm test` — run the suite
- `src/ghost/missing.ts` — the core module
EOF
grepv "codex phantom path caught"     "does not exist"   "$CB" --platform codex
grepv "codex unmarked command caught" "no (verified)"    "$CB" --platform codex
grepv "codex missing stamp caught"    "generation stamp" "$CB" --platform codex
want 1 "codex lying map exits 1" "$CB" --platform codex

# codex: nested budget blowout
python3 -c "open('$CB/src/api/AGENTS.md','w').write('x line\n' * 130)"
grepv "codex nested budget blowout caught" "over budget" "$CB" --platform codex

# codex: root budget overflow
CR="$TMP/codex-rootbudget"; mkdir -p "$CR"
python3 -c "open('$CR/AGENTS.md','w').write('<!-- generated by auto-map v0.1.0 -->\n' + 'x line\n' * 160)"
grepv "codex root budget overflow caught" "over budget" "$CR" --platform codex

# codex: expected significant dir has no nested AGENTS.md
mkdir -p "$CG/src/db"
grepv "codex unmapped significant dir caught" "no nested AGENTS.md" "$CG" --platform codex --expect-dirs "src/db"

# codex: failing command caught under --run-commands
CF="$TMP/codex-cmd"; mkdir -p "$CF"
printf '<!-- generated by auto-map v0.1.0 -->\n# P\n- `npm run definitely-not-a-script` — build\n' > "$CF/AGENTS.md"
grepv "codex failing command caught (--run-commands)" "FAILS when executed" "$CF" --platform codex --run-commands

# unsupported platform → STOP (exit 2), never default to a write target
want 2 "unsupported platform exits 2" "$CG" --platform windsurf

# ══ dual: BOTH trees verified independently; target NEVER mutated ══
DG="$TMP/dual-good"; mkdir -p "$DG/src/api" "$DG/.claude/rules"
cat > "$DG/CLAUDE.md" <<'EOF'
<!-- generated by auto-map v0.1.0 -->
# Proj
Small demo service.
## Commands
- `npm test` — run the suite (verified: 2026-07-06)
## Layout
- `src/api/` — HTTP handlers (see its CLAUDE.md)
EOF
cat > "$DG/AGENTS.md" <<'EOF'
<!-- generated by auto-map v0.1.0 | platform: codex -->
# Proj
Small demo service.
## Commands
- `npm test` — run the suite (verified: 2026-07-06)
## Layout
- `src/api/` — HTTP handlers (see its AGENTS.md)
EOF
cat > "$DG/.claude/rules/api.md" <<'EOF'
---
paths:
  - "src/api/**"
---
# API conventions
Validate all input at the boundary.
EOF
cat > "$DG/src/api/CLAUDE.md" <<'EOF'
<!-- generated by auto-map v0.1.0 -->
# src/api
HTTP handlers. Go through `src/api/index.ts`.
EOF
cat > "$DG/src/api/AGENTS.md" <<'EOF'
<!-- generated by auto-map v0.1.0 | platform: codex -->
# src/api
HTTP handlers. Go through `src/api/index.ts`.
EOF
touch "$DG/src/api/index.ts"
want 0 "dual verifies clean when BOTH trees are valid" "$DG" --platform dual
want 0 "dual: expected dir mapped on both surfaces" "$DG" --platform dual --expect-dirs "src/api"

# dual is READ-ONLY: verify makes zero writes (cksum is POSIX on macOS + Linux)
snap() { find "$1" -type f | sort | while read -r f; do cksum "$f"; done; }
before=$(snap "$DG")
node "$V" "$DG" --platform dual >/dev/null 2>&1
after=$(snap "$DG")
if [ "$before" = "$after" ]; then echo "PASS dual verify made no writes to the target"; else { echo "FAIL dual verify mutated the target"; fails=$((fails+1)); }; fi

# dual verifies each surface independently: a clean CLAUDE tree + a LYING AGENTS.md still fails
DB="$TMP/dual-bad-codex"; mkdir -p "$DB/.claude/rules"
cat > "$DB/CLAUDE.md" <<'EOF'
<!-- generated by auto-map v0.1.0 -->
# Proj
## Commands
- `npm test` — run the suite (verified: 2026-07-06)
EOF
cat > "$DB/AGENTS.md" <<'EOF'
<!-- generated by auto-map v0.1.0 -->
# Proj
- `src/ghost/missing.ts` — the core module
EOF
grepv "dual catches a lie in the AGENTS.md surface"                 "does not exist" "$DB" --platform dual
want 1 "dual exits 1 for a lying AGENTS.md despite a clean CLAUDE.md" "$DB" --platform dual

# dual requires BOTH root maps: a missing AGENTS.md root → exit 2
DM="$TMP/dual-missing-agents"; mkdir -p "$DM"
printf '<!-- generated by auto-map v0.1.0 -->\n# P\n' > "$DM/CLAUDE.md"
want 2 "dual exits 2 when the AGENTS.md root is missing" "$DM" --platform dual

# claude regression stays green: the original $G map still verifies under an explicit --platform claude
want 0 "explicit --platform claude keeps the Claude map green" "$G" --platform claude

echo ""
if [ "$fails" -gt 0 ]; then echo "✗ $fails map-verify test(s) failed"; exit 1; fi
echo "✓ all map-verify contract tests pass"
