#!/bin/bash
# test-map-verify.sh — behavior contract for auto-map's anti-lie gate (CI-run).
# The verifier must PASS a correct disclosure-tiered map and CATCH every class of lie:
# phantom paths, launch-time @imports, budget blowouts, unscoped rules, unmarked commands,
# missing stamps, and unmapped significant directories.
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
V="$ROOT/auto-map/scripts/verify-map.mjs"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
fails=0
want() { # want <rc> <desc> <args...>
  local rc=$1 desc=$2; shift 2
  node "$V" "$@" >/dev/null 2>&1
  local got=$?
  [ "$got" = "$rc" ] && echo "PASS ($got) $desc" || { echo "FAIL (got $got want $rc) $desc"; fails=$((fails+1)); }
}
grepv() { # grepv <desc> <pattern> <args...>
  local desc=$1 pat=$2; shift 2
  if node "$V" "$@" 2>&1 | grep -q "$pat"; then echo "PASS (caught) $desc"; else { echo "FAIL (not caught) $desc"; fails=$((fails+1)); }; fi
}

# ── GOOD map: tiered, stamped, scoped, real paths, marked commands ──
G="$TMP/good"; mkdir -p "$G/src/api" "$G/.claude/rules"
cat > "$G/CLAUDE.md" <<'EOF'
<!-- generated by auto-map v0.1.0 -->
# Proj
Small demo service.
## Commands
- `npm test` — run the suite (verified: 2026-07-06)
## Layout
- `src/api/` — HTTP handlers (see its CLAUDE.md)
EOF
cat > "$G/.claude/rules/api.md" <<'EOF'
---
paths:
  - "src/api/**"
---
# API conventions
Validate all input at the boundary.
EOF
cat > "$G/src/api/CLAUDE.md" <<'EOF'
<!-- generated by auto-map v0.1.0 -->
# src/api
HTTP handlers. Never touch the DB directly — go through `src/api/index.ts`.
EOF
touch "$G/src/api/index.ts"
want 0 "correct tiered map verifies clean" "$G"

# ── LIES: each class must be caught ──
B="$TMP/bad"; mkdir -p "$B/src/api" "$B/.claude/rules"
cat > "$B/CLAUDE.md" <<'EOF'
# Proj
See @docs/architecture.md for detail.
- `npm test` — run the suite
- `src/ghost/missing.ts` — the core module
EOF
cat > "$B/.claude/rules/api.md" <<'EOF'
# API conventions (no paths frontmatter — loads every session)
Rule text.
EOF
grepv "phantom path caught"        "does not exist"        "$B"
grepv "@import caught"             "imports load AT LAUNCH" "$B"
grepv "unmarked command caught"    "no (verified)"          "$B"
grepv "missing stamp caught"       "generation stamp"       "$B"
grepv "unscoped rules file caught" "paths:"                 "$B"
want 1 "lying map exits 1" "$B"

# budget blowout
python3 -c "open('$B/src/api/CLAUDE.md','w').write('x line\n' * 130)"
grepv "nested budget blowout caught" "over budget" "$B"

# expected significant dirs
mkdir -p "$G/src/db"
grepv "unmapped significant dir caught" "no nested CLAUDE.md" "$G" --expect-dirs "src/db"
want 0 "expected dir satisfied when mapped is absent from list" "$G" --expect-dirs "src/api"

# command execution mode: failing command caught
F="$TMP/cmd"; mkdir -p "$F"
printf '<!-- generated by auto-map v0.1.0 -->\n# P\n- `npm run definitely-not-a-script` — build\n' > "$F/CLAUDE.md"
grepv "failing command caught (--run-commands)" "FAILS when executed" "$F" --run-commands

# no map at all
want 2 "no map exits 2" "$TMP/empty-$$-nonexistent" 2>/dev/null || true
mkdir -p "$TMP/nomap" && want 2 "dir without CLAUDE.md exits 2" "$TMP/nomap"

echo ""
if [ "$fails" -gt 0 ]; then echo "✗ $fails map-verify test(s) failed"; exit 1; fi
echo "✓ all map-verify contract tests pass"
